version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install --no-cache-dir -r requirements.txt
workflows:
  build_test_deploy:
    jobs:
      - build
