version: 2.1
orbs:
  snyk: snyk/snyk@2.2.0
jobs:
  build_test:
    docker:
      - image: cimg/python:3.12.2
    steps:
      - checkout
      - run:
          name: Install Fixed Dependencies
          command: pip install --no-cache-dir -r requirements.txt
      - snyk/scan
      - run:
          name: Run Unit Tests
          command: pytest
workflows:
  build_test_deploy:
    jobs:
      - build_test
