version: 2.1
orbs:
  snyk: snyk/snyk@2.2.0
jobs:
  build_test:
    docker:
      - image: cimg/python:3.12.2
    steps:
      - checkout
      - run:
          name: Install Fixed Dependencies
          command: pip install --no-cache-dir -r requirements.txt
      - snyk/scan
      - run:
          name: Run Unit Tests
          command: pytest
  build_push_image:
    docker:
      - image: cimg/python:3.12.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Scan Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/app:latest .
      - snyk/scan:
          docker-image-name: "$DOCKERHUB_USERNAME/app:latest"
          monitor-on-build: true
      - run:
          name: Push Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/app:latest .
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/app:latest
workflows:
  build_test_deploy:
    jobs:
      - build_test
      - build_push_image:
          requires:
            - build_test
